### ISSUE TITLE
Constructing a RTCIceServer fails on W10 Pro N 1803 without the media feature pack

### ISSUE THREAD

**Issue by Trolldemorted** [webrtc-uwp/webrtc-uwp-sdk#52]
```
UnhandledException System.IO.FileNotFoundException occured (Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E)):
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Org.WebRtc.RTCIceServer..ctor()
```

Could you support Windows N too? Not sure how many dependencies are missing without the MFP.

**Comment by jamescadd** [comment]
What's the scenario you want to support on N? Are you looking for a DataChannel only build?

**Comment by Trolldemorted** [comment]
The best case would naturally be that everything works, but I don't know which APIs are missing and on which APIs webrtc depends.

**Comment by jamescadd** [comment]
I think the issue is that without MFP the OS doesn't have the H.264 codec (along with many others), and since we rely on the OS for that codec it can't render/encode video.  We are interested in providing a more modular approach to building WebRTC in the future that would enable these scenarios but it's not a short term goal.  Is installing MFP not possible in this situation?

**Comment by Trolldemorted** [comment]
It is surely possible for me (though you could throw a different exception or a set a different message, it took me a while to grasp what could cause this exception.

Not sure whether average joe knows what the media feature pack is, let alone to install it. A long-term goal to support W10 N without MFP would be great! Some clients may also be unable to install the MFP due to corporate administration.

**Comment by jamescadd** [comment]
Yeah that error message was not helpful.  We'll work on improving this and leave the issue open, if anyone else hits this in the meantime let us know.
